"""Constants for DiveraControl Integration."""

# general
DOMAIN = "diveracontrol"
VERSION = "0"
MINOR_VERSION = "9"
PATCH_VERSION = "2"
MANUFACTURER = "Divera GmbH"
UPDATE_INTERVAL_DATA = 60
UPDATE_INTERVAL_ALARM = 30
DEFAULT_COORDINATOR = "coordinator"
DEFAULT_API = "api"
DEFAULT_SENSORS = "sensors"
DEFAULT_DEVICE_TRACKER = "device_tracker"
LOG_FILE = "home-assistant.log"

# api
BASE_API_URL = "https://app.divera247.com/"
BASE_API_V2_URL = "api/v2/"
API_ACCESS_KEY = "accesskey"
API_AUTH_LOGIN = "auth/login"
API_PULL_ALL = "pull/all"
API_ALARM = "alarms"
API_EVENT = "event"
API_MESSAGES = "messages"
API_USING_VEHICLE_SET_SINGLE = "using-vehicles/set-status"
API_USING_VEHICLE_PROP = "using-vehicle-property"
API_USING_VEHICLE_CREW = "using-vehicle-crew"

# data
D_UPDATE_INTERVAL_DATA = "update_interval_data"
D_UPDATE_INTERVAL_ALARM = "update_interval_alarm"
D_DATA = "data"
D_NAME = "name"
D_API_KEY = "api_key"
D_USERGROUP_ID = "usergroup_id"
D_UCR = "ucr"
D_UCR_ID = "ucr_id"
D_CLUSTER_NAME = "cluster_name"
D_COORDINATOR = "coordinator"
D_OPEN_ALARMS = "open_alarms"
D_UCR_DEFAULT = "ucr_default"
D_UCR_ACTIVE = "ucr_active"
D_TS = "ts"
D_USER = "user"
D_STATUS = "status"
D_CLUSTER = "cluster"
D_MONITOR = "monitor"
D_ALARM = "alarm"
D_NEWS = "news"
D_EVENTS = "events"
D_DM = "dm"
D_MESSAGE_CHANNEL = "message_channel"
D_MESSAGE = "message"
D_LOCALMONITOR = "localmonitor"
D_STATUSPLAN = "statusplan"
D_ACCESS = "access"
D_VEHICLE = "vehicle"

# permissions
PERM_MESSAGES = "messages"
PERM_ALARM = "alarm"
PERM_STATUS_VEHICLE = "status_vehicle"
PERM_MANAGEMENT = "management"

# icons
I_OPEN_ALARM = "mdi:alarm-light-outline"
I_OPEN_ALARM_NOPRIO = "mdi:alarm-light-off-outline"
I_CLOSED_ALARM = "mdi:check-circle-outline"
I_VEHICLE = "mdi:fire-truck"
I_FIRESTATION = "mdi:fire-station"
I_COUNTER_ACTIVE_ALARMS = "mdi:counter"
I_AVAILABILITY = "mdi:run-fast"
