name: 🏠 Home Assistant Quality Checks

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hass:
    name: HASS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
