name: Validate and Prepare Release Branch

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - release

jobs:
  prepare_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure Correct Folder Structure
        run: |
          mkdir -p config/custom_components/diveracontrol
          mv manifest.json config/custom_components/diveracontrol/ || true
          mv *.py config/custom_components/diveracontrol/ || true
          mv services.yaml config/custom_components/diveracontrol/ || true
          mv README.md config/custom_components/diveracontrol/ || true