name: Validate integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hass:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"

  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
