name: Validate integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  schedule:
    - cron:  '0 0 * * *'

jobs:
  hass:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"

  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"